# Generated by Django 4.2.3 on 2023-07-30 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carshowroom", "0002_purchase_delete_carcategory_remove_car_engine_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
    ]
