# Generated by Django 4.2.3 on 2023-07-30 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carshowroom", "0003_rename_first_name_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="showroom",
        ),
    ]
