# Generated by Django 4.2.3 on 2023-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshowroom", "0005_brand_showroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(to="carshowroom.feature"),
        ),
    ]
